# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

# mybatis
mybatis:
  mapper-locations: classpath*:com.smart.future.dao/**/*.xml
