# 端口配置
server:
  port: 3000
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  # 文件上传配置
  servlet:
    multipart:
      location: d:\tmp
      max-file-size: 1049610000
      max-request-size: 1049610000
upload:
  temp-path: D:\upload\temp
  real-path: D:\upload\real

# mybatis
mybatis:
  mapper-locations: classpath*:com.smart.future.dao/**/*.xml

