# 端口配置
server:
  port: 9000
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/smart?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  # 文件上传配置
  servlet:
    multipart:
      location: /tmp
      max-file-size: 1049610000
      max-request-size: 1049610000
#  resources:
#    static-locations: classpath:static/,file:static/
upload:
  temp-path: /usr/local/smart/resource/temp
  real-path: /usr/local/smart/resource/real


# mybatis
mybatis:
  mapper-locations: classpath*:com.smart.future.dao/**/*.xml

